<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>4aa0ea2a-d708-48ca-a347-cde8cac480db</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BmWms.Core\BmWms.Core.csproj" />
		<ProjectReference Include="..\BmWms.Infrastructure\BmWms.Infrastructure.csproj" />
	</ItemGroup>

</Project>